import io
from typing import List, Optional

try:
    from docx import Document as DocxDocument
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    HAS_DOCX = True
except ImportError:
    HAS_DOCX = False

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib.colors import HexColor, black, white
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    )
    from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False


def build_redlined_docx(contract_filename: str, clauses: list, accepted_only: bool = False) -> bytes:
    """Build a Word document with all redline suggestions."""
    if not HAS_DOCX:
        return b"python-docx not available"

    doc = DocxDocument()

    # Title
    title = doc.add_heading("LEXGUARD — Contract Redline Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(f"Document: {contract_filename}")
    doc.add_paragraph(f"Generated by LEXGUARD AI — For review purposes only.")
    doc.add_paragraph("⚠ This is an AI-generated analysis tool, not legal advice.")
    doc.add_paragraph("")

    filter_clauses = clauses
    if accepted_only:
        filter_clauses = [c for c in clauses if c.get("is_accepted") is True]

    if not filter_clauses:
        doc.add_paragraph("No redline suggestions available.")
    else:
        for i, clause in enumerate(filter_clauses):
            doc.add_heading(f"{i+1}. {clause.get('clause_type', 'Clause')}", level=2)

            # Risk badge
            risk_para = doc.add_paragraph()
            risk_run = risk_para.add_run(f"Risk Level: {clause.get('risk_level', 'unknown').upper()} | Score: {clause.get('risk_score', 0):.0f}/25")
            risk_run.bold = True

            # Why risky
            if clause.get("why_risky"):
                p = doc.add_paragraph()
                p.add_run("Issue: ").bold = True
                p.add_run(clause.get("why_risky", ""))

            # Original text
            doc.add_paragraph()
            orig_head = doc.add_paragraph()
            orig_head.add_run("ORIGINAL TEXT:").bold = True
            orig_text = doc.add_paragraph(clause.get("raw_text", ""))

            # Redline suggestion
            doc.add_paragraph()
            red_head = doc.add_paragraph()
            red_run = red_head.add_run("SUGGESTED REVISION:")
            red_run.bold = True
            red_run.font.color.rgb = RGBColor(0x00, 0xA0, 0x50)
            red_text = doc.add_paragraph(clause.get("redline_suggestion", "No suggestion available."))

            doc.add_paragraph("─" * 60)
            doc.add_paragraph()

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.read()


def build_risk_report_pdf(contract: dict, clauses: list) -> bytes:
    """Build a professional risk report PDF using reportlab."""
    if not HAS_REPORTLAB:
        return b"reportlab not available"

    buffer = io.BytesIO()
    doc_template = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
    )

    styles = getSampleStyleSheet()
    gold = HexColor("#E8C547")
    danger = HexColor("#FF4444")
    safe = HexColor("#00D084")
    warning = HexColor("#FF8C00")
    dark = HexColor("#1A1A2E")

    def risk_color(level: str):
        return {"high": danger, "moderate": warning, "low": safe}.get(level, HexColor("#888888"))

    story = []

    # Header
    title_style = ParagraphStyle(
        "Title", parent=styles["Title"],
        textColor=dark, fontSize=22, spaceAfter=6
    )
    story.append(Paragraph("LEXGUARD AI", title_style))
    story.append(Paragraph("Contract Risk Intelligence Report", styles["Heading2"]))
    story.append(HRFlowable(width="100%", thickness=2, color=gold, spaceAfter=12))

    # Metadata
    meta_data = [
        ["Document", contract.get("original_filename", "Unknown")],
        ["Contract Type", contract.get("contract_type", "Unknown")],
        ["Analyzed", contract.get("created_at", "")[:10] if contract.get("created_at") else "—"],
        ["Overall Risk", contract.get("risk_level", "unknown").upper()],
        ["Risk Score (CRI)", f"{contract.get('aggregate_risk_index', 0):.0f} / 100"],
        ["Clauses Flagged", str(len(clauses))],
    ]
    meta_table = Table(meta_data, colWidths=[2 * inch, 4 * inch])
    meta_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), HexColor("#F0F0F0")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#CCCCCC")),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 0.2 * inch))

    # Executive Summary
    story.append(Paragraph("Executive Summary", styles["Heading2"]))
    summary_text = contract.get("executive_summary", "No summary available.")
    story.append(Paragraph(summary_text, styles["Normal"]))
    story.append(Spacer(1, 0.2 * inch))

    # Risk Breakdown
    story.append(Paragraph("Risk Breakdown", styles["Heading2"]))
    breakdown = [
        ["Risk Level", "Count", "% of Total"],
        ["HIGH", str(contract.get("high_count", 0)), f"{contract.get('high_count', 0) / max(len(clauses), 1) * 100:.0f}%"],
        ["MODERATE", str(contract.get("moderate_count", 0)), f"{contract.get('moderate_count', 0) / max(len(clauses), 1) * 100:.0f}%"],
        ["LOW", str(contract.get("low_count", 0)), f"{contract.get('low_count', 0) / max(len(clauses), 1) * 100:.0f}%"],
    ]
    breakdown_table = Table(breakdown, colWidths=[2 * inch, 2 * inch, 2 * inch])
    breakdown_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), dark),
        ("TEXTCOLOR", (0, 0), (-1, 0), white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BACKGROUND", (0, 1), (-1, 1), HexColor("#FF444422")),
        ("BACKGROUND", (0, 2), (-1, 2), HexColor("#FF8C0022")),
        ("BACKGROUND", (0, 3), (-1, 3), HexColor("#00D08422")),
        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#CCCCCC")),
        ("PADDING", (0, 0), (-1, -1), 8),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
    ]))
    story.append(breakdown_table)
    story.append(Spacer(1, 0.2 * inch))

    # All Clauses
    story.append(Paragraph("Flagged Clauses", styles["Heading2"]))
    for i, clause in enumerate(clauses):
        clause_header = f"{i+1}. {clause.get('clause_type', 'Unknown')} [{clause.get('risk_level', 'unknown').upper()}]"
        story.append(Paragraph(clause_header, styles["Heading3"]))
        story.append(Paragraph(f"<b>Risk Score:</b> {clause.get('risk_score', 0):.0f}/25 | <b>Category:</b> {clause.get('category', 'Unknown')}", styles["Normal"]))
        story.append(Paragraph(f"<b>Plain English:</b> {clause.get('plain_english', '')}", styles["Normal"]))
        story.append(Paragraph(f"<b>Why Risky:</b> {clause.get('why_risky', '')}", styles["Normal"]))
        story.append(Spacer(1, 0.1 * inch))

    # Footer
    story.append(HRFlowable(width="100%", thickness=1, color=HexColor("#CCCCCC"), spaceBefore=12))
    story.append(Paragraph(
        "⚠ This report was generated by LEXGUARD AI for awareness purposes only. It is not a substitute for professional legal advice. Consult a licensed attorney before making any decisions based on this analysis.",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=HexColor("#888888"))
    ))

    doc_template.build(story)
    buffer.seek(0)
    return buffer.read()
