'use client'

import { useEffect, useState } from 'react'
import { Shield, Activity, Hash } from 'lucide-react'

function useTraceId() {
  const [traceId, setTraceId] = useState('')
  useEffect(() => {
    const stored = sessionStorage.getItem('lg_trace_id')
    if (stored) { setTraceId(stored); return }
    const id = 'LG-' + Math.random().toString(36).substring(2, 10).toUpperCase() + '-' + Date.now().toString(36).toUpperCase()
    sessionStorage.setItem('lg_trace_id', id)
    setTraceId(id)
  }, [])
  return traceId
}

function useHealthMetrics() {
  const [latency, setLatency] = useState<number | null>(null)
  const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'
  useEffect(() => {
    let cancelled = false
    const ping = async () => {
      try {
        const t0 = performance.now()
        await fetch(`${API_URL}/health`, { cache: 'no-store' })
        if (!cancelled) setLatency(Math.round(performance.now() - t0))
      } catch { if (!cancelled) setLatency(null) }
    }
    ping()
    const id = setInterval(ping, 30000)
    return () => { cancelled = true; clearInterval(id) }
  }, [API_URL])
  return { latency }
}

export function LegalFooter() {
  const traceId = useTraceId()
  const { latency } = useHealthMetrics()

  return (
    <footer className="border-t border-white/[0.05] bg-bg-surface/50 backdrop-blur-sm">
      {/* Disclaimer Banner */}
      <div className="bg-gold/5 border-b border-gold/10 px-6 py-2">
        <div className="max-w-7xl mx-auto flex items-start gap-2.5">
          <Shield className="w-3.5 h-3.5 text-gold flex-shrink-0 mt-0.5" />
          <p className="text-xs text-text-muted leading-relaxed">
            <span className="text-gold font-semibold">AI Legal Assistant Disclaimer: </span>
            LEXGUARD is an AI-powered contract intelligence tool and is{' '}
            <strong className="text-text-secondary">not a licensed legal practitioner</strong>. All analysis,
            risk scores, and redline suggestions are generated by artificial intelligence for informational
            purposes only and do not constitute legal advice. Always consult a qualified attorney before
            making decisions based on this analysis.
          </p>
        </div>
      </div>

      {/* System Health + Trace */}
      <div className="px-6 py-2.5">
        <div className="max-w-7xl mx-auto flex items-center justify-between flex-wrap gap-3">
          {/* Left: Health metrics */}
          <div className="flex items-center gap-5">
            <div className="flex items-center gap-1.5">
              <Activity className="w-3 h-3 text-text-muted" />
              <span className="text-xs text-text-muted">API Latency:</span>
              <span className={`text-xs font-mono font-medium ${
                latency === null ? 'text-text-muted' :
                latency < 300 ? 'text-safe' :
                latency < 800 ? 'text-warning' : 'text-danger'
              }`}>
                {latency === null ? '—' : `${latency}ms`}
              </span>
            </div>

            <div className="flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-safe animate-pulse" />
              <span className="text-xs text-text-muted">LLM Provider:</span>
              <span className="text-xs font-mono text-text-secondary">Groq / LLaMA-3.3-70B</span>
            </div>

            <div className="hidden sm:flex items-center gap-1.5">
              <span className="text-xs text-text-muted">Model:</span>
              <span className="text-xs font-mono text-text-secondary">llama-3.3-70b-versatile</span>
            </div>
          </div>

          {/* Right: Trace ID + version */}
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-1.5">
              <Hash className="w-3 h-3 text-text-muted" />
              <span className="text-xs text-text-muted">Trace:</span>
              <span className="text-xs font-mono text-text-secondary tracking-wider">{traceId || '—'}</span>
            </div>
            <div className="hidden sm:flex items-center gap-1.5">
              <span className="text-xs text-text-muted">v1.0.0</span>
              <span className="text-xs text-text-muted">·</span>
              <span className="text-xs text-text-muted">© 2026 LEXGUARD AI</span>
            </div>
          </div>
        </div>
      </div>
    </footer>
  )
}
